# reference is at https://docs.docker.com/compose/compose-file/build/
version: "3.3"
services:
  # the api server
  petstore:
    container_name: petstore
    image: swaggerapi/petstore
    environment:
      SWAGGER_HOST: http://petstore.swagger.io
      SWAGGER_URL: http://localhost
      SWAGGER_BASE_PATH: /v2
    ports: ['8080:8080']

  # the dotnet container
  grader:
    container_name: grader
    depends_on: [petstore]
    image: wethinkcode/grader-dotnet:latest
    environment: {}
    command: /app/clean-restore-test.sh
    volumes:
      - ${PWD}:/app